[workspace]
authors = ["rishikanthkc <rishikanth2077@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "life"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025101405,<0.26"
python = ">=3.11,<3.13"
pygame = ">=2.6.1,<3"
